version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - '8000:80'
